/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeshield.dev/auditor/apis/auditor/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAuditRegistrations implements AuditRegistrationInterface
type FakeAuditRegistrations struct {
	Fake *FakeAuditorV1alpha1
	ns   string
}

var auditregistrationsResource = schema.GroupVersionResource{Group: "auditor.kubeshield.to", Version: "v1alpha1", Resource: "auditregistrations"}

var auditregistrationsKind = schema.GroupVersionKind{Group: "auditor.kubeshield.to", Version: "v1alpha1", Kind: "AuditRegistration"}

// Get takes name of the auditRegistration, and returns the corresponding auditRegistration object, and an error if there is any.
func (c *FakeAuditRegistrations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AuditRegistration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(auditregistrationsResource, c.ns, name), &v1alpha1.AuditRegistration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AuditRegistration), err
}

// List takes label and field selectors, and returns the list of AuditRegistrations that match those selectors.
func (c *FakeAuditRegistrations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AuditRegistrationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(auditregistrationsResource, auditregistrationsKind, c.ns, opts), &v1alpha1.AuditRegistrationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AuditRegistrationList{ListMeta: obj.(*v1alpha1.AuditRegistrationList).ListMeta}
	for _, item := range obj.(*v1alpha1.AuditRegistrationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested auditRegistrations.
func (c *FakeAuditRegistrations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(auditregistrationsResource, c.ns, opts))

}

// Create takes the representation of a auditRegistration and creates it.  Returns the server's representation of the auditRegistration, and an error, if there is any.
func (c *FakeAuditRegistrations) Create(ctx context.Context, auditRegistration *v1alpha1.AuditRegistration, opts v1.CreateOptions) (result *v1alpha1.AuditRegistration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(auditregistrationsResource, c.ns, auditRegistration), &v1alpha1.AuditRegistration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AuditRegistration), err
}

// Update takes the representation of a auditRegistration and updates it. Returns the server's representation of the auditRegistration, and an error, if there is any.
func (c *FakeAuditRegistrations) Update(ctx context.Context, auditRegistration *v1alpha1.AuditRegistration, opts v1.UpdateOptions) (result *v1alpha1.AuditRegistration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(auditregistrationsResource, c.ns, auditRegistration), &v1alpha1.AuditRegistration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AuditRegistration), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAuditRegistrations) UpdateStatus(ctx context.Context, auditRegistration *v1alpha1.AuditRegistration, opts v1.UpdateOptions) (*v1alpha1.AuditRegistration, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(auditregistrationsResource, "status", c.ns, auditRegistration), &v1alpha1.AuditRegistration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AuditRegistration), err
}

// Delete takes name of the auditRegistration and deletes it. Returns an error if one occurs.
func (c *FakeAuditRegistrations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(auditregistrationsResource, c.ns, name), &v1alpha1.AuditRegistration{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAuditRegistrations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(auditregistrationsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AuditRegistrationList{})
	return err
}

// Patch applies the patch and returns the patched auditRegistration.
func (c *FakeAuditRegistrations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AuditRegistration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(auditregistrationsResource, c.ns, name, pt, data, subresources...), &v1alpha1.AuditRegistration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AuditRegistration), err
}
